name: DoxaRpgSystem
version: '${project.version}'
main: fir.sec.thi.doxarpgsystem.Doxaplg01
api-version: 1.18
commands:
  스탯:
    description: /stat error
  수표:
    description: /수표 [금액] [수량]
  mobspawn:
    description: /mobspawn Name Level EntityType Speed Attack Health
    permission: your